name: bathu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_custom_carousel_slider: ^1.2.0
  smooth_star_rating_null_safety: ^1.0.4+2

 

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/carousel/1.png
    - assets/images/carousel/2.png
    - assets/images/carousel/3.png
    - assets/images/carousel/4.png
    - assets/images/secondCarousel/1.jpg
    - assets/images/secondCarousel/2.jpg
    - assets/images/secondCarousel/3.jpg
    #Journey
    - assets/images/shoes/journey/express/1.png
    - assets/images/shoes/journey/express/2.png
    - assets/images/shoes/journey/express/3.png
    - assets/images/shoes/journey/floral/1.png
    - assets/images/shoes/journey/floral/2.png
    - assets/images/shoes/journey/floral/3.png
    - assets/images/shoes/journey/white/1.png
    - assets/images/shoes/journey/white/2.png
    - assets/images/shoes/journey/white/3.png
    #MoonLight
    - assets/images/shoes/moonlight/black/1.png
    - assets/images/shoes/moonlight/black/2.png
    - assets/images/shoes/moonlight/black/3.png
    - assets/images/shoes/moonlight/pink/1.png
    - assets/images/shoes/moonlight/pink/2.png
    - assets/images/shoes/moonlight/pink/3.png
    - assets/images/shoes/moonlight/purple/1.png
    - assets/images/shoes/moonlight/purple/2.png
    - assets/images/shoes/moonlight/purple/3.png
    #Mesh Ed
    - assets/images/shoes/mesh/berry/1.png
    - assets/images/shoes/mesh/berry/2.png
    - assets/images/shoes/mesh/berry/3.png
    - assets/images/shoes/mesh/black/1.png
    - assets/images/shoes/mesh/black/2.png
    - assets/images/shoes/mesh/black/3.png
    - assets/images/shoes/mesh/blackNWhite/1.png
    - assets/images/shoes/mesh/blackNWhite/2.png
    - assets/images/shoes/mesh/blackNWhite/3.png
    - assets/images/shoes/mesh/blue/1.png
    - assets/images/shoes/mesh/blue/2.png
    - assets/images/shoes/mesh/blue/3.png
    - assets/images/shoes/mesh/green/1.png
    - assets/images/shoes/mesh/grey/1.png
    - assets/images/shoes/mesh/grey/2.png
    - assets/images/shoes/mesh/grey/3.png
    - assets/images/shoes/mesh/halfBlack/1.png
    - assets/images/shoes/mesh/halfBlack/3.png
    - assets/images/shoes/mesh/halfBlue/1.png
    - assets/images/shoes/mesh/halfBlue/2.png
    - assets/images/shoes/mesh/halfBlue/3.png    
    - assets/images/shoes/mesh/halfGreen/1.png
    - assets/images/shoes/mesh/halfGreen/2.png
    - assets/images/shoes/mesh/halfGreen/3.png    
    - assets/images/shoes/mesh/halfGrey/1.png
    - assets/images/shoes/mesh/halfGrey/2.png
    - assets/images/shoes/mesh/halfGrey/3.png
    - assets/images/shoes/mesh/halfOrange/1.png
    - assets/images/shoes/mesh/halfOrange/2.png
    - assets/images/shoes/mesh/halfOrange/3.png    
    - assets/images/shoes/mesh/halfPink/1.png
    - assets/images/shoes/mesh/halfPink/3.png
    - assets/images/shoes/mesh/halfRed/1.png
    - assets/images/shoes/mesh/halfRed/2.png
    - assets/images/shoes/mesh/halfRed/3.png
    - assets/images/shoes/mesh/halfWhite/1.png
    - assets/images/shoes/mesh/halfWhite/2.png
    - assets/images/shoes/mesh/halfWhite/3.png
    - assets/images/shoes/mesh/halfYellow/1.png
    - assets/images/shoes/mesh/halfYellow/2.png
    - assets/images/shoes/mesh/halfYellow/3.png
    - assets/images/shoes/mesh/hazel/1.png
    - assets/images/shoes/mesh/hazel/2.png
    - assets/images/shoes/mesh/hazel/3.png
    - assets/images/shoes/mesh/lightBlue/1.png
    - assets/images/shoes/mesh/lightBlue/2.png
    - assets/images/shoes/mesh/lightBlue/3.png
    - assets/images/shoes/mesh/orange/1.png
    - assets/images/shoes/mesh/pink/1.png
    - assets/images/shoes/mesh/pink/3.png
    - assets/images/shoes/mesh/red/1.png
    - assets/images/shoes/mesh/red/2.png
    - assets/images/shoes/mesh/red/3.png
    - assets/images/shoes/mesh/redNWhite/1.png
    - assets/images/shoes/mesh/redNWhite/2.png
    - assets/images/shoes/mesh/redNWhite/3.png
    - assets/images/shoes/mesh/rosePink/1.png
    - assets/images/shoes/mesh/rosePink/2.png
    - assets/images/shoes/mesh/rosePink/3.png
    - assets/images/shoes/mesh/white/1.png
    - assets/images/shoes/mesh/white/2.png
    - assets/images/shoes/mesh/white/3.png
    - assets/images/shoes/mesh/yellow/1.png
    - assets/images/shoes/mesh/yellow/2.png
    - assets/images/shoes/mesh/yellow/3.png   
    #SKY Ed
    - assets/images/shoes/sky/black/1.png
    - assets/images/shoes/sky/black/2.png
    - assets/images/shoes/sky/black/3.png
    - assets/images/shoes/sky/blue/1.png
    - assets/images/shoes/sky/blue/2.png
    - assets/images/shoes/sky/blue/3.png
    - assets/images/shoes/sky/green/1.png
    - assets/images/shoes/sky/green/2.png
    - assets/images/shoes/sky/green/3.png
    - assets/images/shoes/sky/grey/1.png
    - assets/images/shoes/sky/grey/2.png
    - assets/images/shoes/sky/grey/3.png
    - assets/images/shoes/sky/lightBlue/1.png
    - assets/images/shoes/sky/lightBlue/2.png
    - assets/images/shoes/sky/lightBlue/3.png
    - assets/images/shoes/sky/lotus/1.png
    - assets/images/shoes/sky/lotus/2.png
    - assets/images/shoes/sky/lotus/3.png
    - assets/images/shoes/sky/orange/1.png
    - assets/images/shoes/sky/orange/2.png
    - assets/images/shoes/sky/orange/3.png
    - assets/images/shoes/sky/pink/1.png
    - assets/images/shoes/sky/pink/2.png
    - assets/images/shoes/sky/pink/3.png
    - assets/images/shoes/sky/red/1.png
    - assets/images/shoes/sky/red/2.png
    - assets/images/shoes/sky/red/3.png
    - assets/images/shoes/sky/white/1.png
    - assets/images/shoes/sky/white/2.png
    - assets/images/shoes/sky/white/3.png
    - assets/images/shoes/sky/yellow/1.png
    - assets/images/shoes/sky/yellow/2.png
    - assets/images/shoes/sky/yellow/3.png
    - assets/images/hist/1.png
    - assets/images/hist/2.png
    - assets/images/hist/3.png
    - assets/images/hist/4.png
    - assets/images/hist/5.png
    - assets/images/testimonials/1.png
    - assets/images/testimonials/2.png
    - assets/images/testimonials/3.png
    - assets/images/testimonials/4.png       
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf
        - asset: assets/fonts/Gilroy-Light.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf  
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
