class ProductList {
  var productList1 = [
    {
      "name": "SKY EDITION - RED",
      "picture1": "assets/images/shoes/sky/red/1.png",
      "picture2": "assets/images/shoes/sky/red/2.png",
      "picture3": "assets/images/shoes/sky/red/3.png",
      "reviews": 14,
      "price": 1200,
    },
    {
      "name": "SKY EDITION - MIDNIGHT BLACK",
      "picture1": "assets/images/shoes/sky/black/1.png",
      "picture2": "assets/images/shoes/sky/black/2.png",
      "picture3": "assets/images/shoes/sky/black/3.png",
      "reviews": 31,
      "price": 1200,
    },
    {
      "name": "SKY EDITION - LIGHT BLUE",
      "picture1": "assets/images/shoes/sky/lightBlue/1.png",
      "picture2": "assets/images/shoes/sky/lightBlue/2.png",
      "picture3": "assets/images/shoes/sky/lightBlue/3.png",
      "reviews": 12,
      "price": 1200,
    },
    {
      "name": "SKY EDITION - GREY & BLACK",
      "picture1": "assets/images/shoes/sky/grey/1.png",
      "picture2": "assets/images/shoes/sky/grey/2.png",
      "picture3": "assets/images/shoes/sky/grey/3.png",
      "reviews": 16,
      "price": 1200,
    },
    {
      "name": "SKY EDITION - YELLOW",
      "picture1": "assets/images/shoes/sky/yellow/1.png",
      "picture2": "assets/images/shoes/sky/yellow/2.png",
      "picture3": "assets/images/shoes/sky/yellow/3.png",
      "reviews": 5,
      "price": 1200,
    },
    {
      "name": "SKY EDITION - ARMY GREEN",
      "picture1": "assets/images/shoes/sky/green/1.png",
      "picture2": "assets/images/shoes/sky/green/2.png",
      "picture3": "assets/images/shoes/sky/green/3.png",
      "reviews": 6,
      "price": 1200,
    },
    {
      "name": "SKY EDITION - SNOW WHITE",
      "picture1": "assets/images/shoes/sky/white/1.png",
      "picture2": "assets/images/shoes/sky/white/2.png",
      "picture3": "assets/images/shoes/sky/white/3.png",
      "reviews": 8,
      "price": 1200,
    },
    {
      "name": "SKY EDITION - NUDE PINK",
      "picture1": "assets/images/shoes/sky/pink/1.png",
      "picture2": "assets/images/shoes/sky/pink/2.png",
      "picture3": "assets/images/shoes/sky/pink/3.png",
      "reviews": 5,
      "price": 1200,
    },
    {
      "name": "SKY EDITION - NAVY BLUE",
      "picture1": "assets/images/shoes/sky/blue/1.png",
      "picture2": "assets/images/shoes/sky/blue/2.png",
      "picture3": "assets/images/shoes/sky/blue/3.png",
      "reviews": 1,
      "price": 1200,
    },
    {
      "name": "SKY EDITION - ORANGE",
      "picture1": "assets/images/shoes/sky/orange/1.png",
      "picture2": "assets/images/shoes/sky/orange/2.png",
      "picture3": "assets/images/shoes/sky/orange/3.png",
      "reviews": 4,
      "price": 1200,
    },
    {
      "name": "SKY EDITION - LOTUS",
      "picture1": "assets/images/shoes/sky/lotus/1.png",
      "picture2": "assets/images/shoes/sky/lotus/2.png",
      "picture3": "assets/images/shoes/sky/lotus/3.png",
      "reviews": 2,
      "price": 1200,
    },
  ];

  var productList2 = [
    {
      "name": "MESH EDITION - FULL BLUE",
      "picture1": "assets/images/shoes/mesh/blue/1.png",
      "picture2": "assets/images/shoes/mesh/blue/2.png",
      "picture3": "assets/images/shoes/mesh/blue/3.png",
      "reviews": 43,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - FULL RED",
      "picture1": "assets/images/shoes/mesh/red/1.png",
      "picture2": "assets/images/shoes/mesh/red/2.png",
      "picture3": "assets/images/shoes/mesh/red/3.png",
      "reviews": 12,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - RED",
      "picture1": "assets/images/shoes/mesh/halfRed/1.png",
      "picture2": "assets/images/shoes/mesh/halfRed/2.png",
      "picture3": "assets/images/shoes/mesh/halfRed/3.png",
      "reviews": 36,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - ARMY GREEN",
      "picture1": "assets/images/shoes/mesh/green/1.png",
      "picture2": "assets/images/shoes/mesh/green/2.png",
      "picture3": "assets/images/shoes/mesh/green/3.png",
      "reviews": 5,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - NAVY BLUE",
      "picture1": "assets/images/shoes/mesh/halfBlue/1.png",
      "picture2": "assets/images/shoes/mesh/halfBlue/2.png",
      "picture3": "assets/images/shoes/mesh/halfBlue/3.png",
      "reviews": 43,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - YELLOW",
      "picture1": "assets/images/shoes/mesh/halfYellow/1.png",
      "picture2": "assets/images/shoes/mesh/halfYellow/2.png",
      "picture3": "assets/images/shoes/mesh/halfYellow/3.png",
      "reviews": 6,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - FULL BLACK",
      "picture1": "assets/images/shoes/mesh/black/1.png",
      "picture2": "assets/images/shoes/mesh/black/2.png",
      "picture3": "assets/images/shoes/mesh/black/3.png",
      "reviews": 13,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - LIGHT BLUE",
      "picture1": "assets/images/shoes/mesh/lightBlue/1.png",
      "picture2": "assets/images/shoes/mesh/lightBlue/2.png",
      "picture3": "assets/images/shoes/mesh/lightBlue/3.png",
      "reviews": 11,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - FULL GREY",
      "picture1": "assets/images/shoes/mesh/grey/1.png",
      "picture2": "assets/images/shoes/mesh/grey/2.png",
      "picture3": "assets/images/shoes/mesh/grey/3.png",
      "reviews": 7,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - GREY",
      "picture1": "assets/images/shoes/mesh/halfGrey/1.png",
      "picture2": "assets/images/shoes/mesh/halfGrey/2.png",
      "picture3": "assets/images/shoes/mesh/halfGrey/3.png",
      "reviews": 19,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - FULL YELLOW",
      "picture1": "assets/images/shoes/mesh/yellow/1.png",
      "picture2": "assets/images/shoes/mesh/yellow/2.png",
      "picture3": "assets/images/shoes/mesh/yellow/3.png",
      "reviews": 2,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - HONEY HAZEL",
      "picture1": "assets/images/shoes/mesh/hazel/1.png",
      "picture2": "assets/images/shoes/mesh/hazel/2.png",
      "picture3": "assets/images/shoes/mesh/hazel/3.png",
      "reviews": 5,
      "price": 1200,
    },
    {
      "name": "MESH EDITION -  BLACK",
      "picture1": "assets/images/shoes/mesh/halfBlack/1.png",
      "picture2": "assets/images/shoes/mesh/halfBlack/2.png",
      "picture3": "assets/images/shoes/mesh/halfBlack/3.png",
      "reviews": 11,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - ARMY GREEN",
      "picture1": "assets/images/shoes/mesh/halfGreen/1.png",
      "picture2": "assets/images/shoes/mesh/halfGreen/2.png",
      "picture3": "assets/images/shoes/mesh/halfGreen/3.png",
      "reviews": 8,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - RACER WHITE",
      "picture1": "assets/images/shoes/mesh/redNWhite/1.png",
      "picture2": "assets/images/shoes/mesh/redNWhite/2.png",
      "picture3": "assets/images/shoes/mesh/redNWhite/3.png",
      "reviews": 5,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - WHITE",
      "picture1": "assets/images/shoes/mesh/white/1.png",
      "picture2": "assets/images/shoes/mesh/white/2.png",
      "picture3": "assets/images/shoes/mesh/white/3.png",
      "reviews": 8,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - BERRY BLAZE",
      "picture1": "assets/images/shoes/mesh/berry/1.png",
      "picture2": "assets/images/shoes/mesh/berry/2.png",
      "picture3": "assets/images/shoes/mesh/berry/3.png",
      "reviews": 0,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - FULL ORANGE",
      "picture1": "assets/images/shoes/mesh/orange/1.png",
      "picture2": "assets/images/shoes/mesh/orange/2.png",
      "picture3": "assets/images/shoes/mesh/orange/3.png",
      "reviews": 1,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - FULL ROSE PINK",
      "picture1": "assets/images/shoes/mesh/rosePink/1.png",
      "picture2": "assets/images/shoes/mesh/rosePink/2.png",
      "picture3": "assets/images/shoes/mesh/rosePink/3.png",
      "reviews": 0,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - YELLOW",
      "picture1": "assets/images/shoes/mesh/yellow/1.png",
      "picture2": "assets/images/shoes/mesh/yellow/2.png",
      "picture3": "assets/images/shoes/mesh/yellow/3.png",
      "reviews": 3,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - ORANGE",
      "picture1": "assets/images/shoes/mesh/halfOrange/1.png",
      "picture2": "assets/images/shoes/mesh/halfOrange/2.png",
      "picture3": "assets/images/shoes/mesh/halfOrange/3.png",
      "reviews": 6,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - FULL PINK",
      "picture1": "assets/images/shoes/mesh/pink/1.png",
      "picture2": "assets/images/shoes/mesh/pink/2.png",
      "picture3": "assets/images/shoes/mesh/pink/3.png",
      "reviews": 1,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - NUDE PINK",
      "picture1": "assets/images/shoes/mesh/halfPink/1.png",
      "picture2": "assets/images/shoes/mesh/halfPink/2.png",
      "picture3": "assets/images/shoes/mesh/halfPink/3.png",
      "reviews": 2,
      "price": 1200,
    },
    {
      "name": "MESH EDITION - WHITE & BLACK",
      "picture1": "assets/images/shoes/mesh/blackNWhite/1.png",
      "picture2": "assets/images/shoes/mesh/blackNWhite/2.png",
      "picture3": "assets/images/shoes/mesh/blackNWhite/3.png",
      "reviews": 3,
      "price": 1200,
    },
  ];

  var productList3 = [
    {
      "name": "JOURNEY REFINED - CRYSTAL WHITE",
      "picture1": "assets/images/shoes/journey/white/1.png",
      "picture2": "assets/images/shoes/journey/white/2.png",
      "picture3": "assets/images/shoes/journey/white/3.png",
      "reviews": 8,
      "price": 1200,
    },
    {
      "name": "JOURNEY REFINED - EXPRESS",
      "picture1": "assets/images/shoes/journey/express/1.png",
      "picture2": "assets/images/shoes/journey/express/2.png",
      "picture3": "assets/images/shoes/journey/express/3.png",
      "reviews": 21,
      "price": 1200,
    },
    {
      "name": "JOURNEY REFINED - FLORAL",
      "picture1": "assets/images/shoes/journey/floral/1.png",
      "picture2": "assets/images/shoes/journey/floral/2.png",
      "picture3": "assets/images/shoes/journey/floral/3.png",
      "reviews": 21,
      "price": 1200,
    },
  ];

  var productList4 = [
    {
      "name": "MOONLIGHT SLIDER - BLACK",
      "picture1": "assets/images/shoes/journey/white/1.png",
      "picture2": "assets/images/shoes/journey/white/2.png",
      "picture3": "assets/images/shoes/journey/white/3.png",
      "reviews": 1,
      "price": 650,
    },
    {
      "name": "MOONLIGHT SLIDER - PURPLE",
      "picture1": "assets/images/shoes/journey/purple/1.png",
      "picture2": "assets/images/shoes/journey/purple/2.png",
      "picture3": "assets/images/shoes/journey/purple/3.png",
      "reviews": 1,
      "price": 650,
    },
    {
      "name": "MOONLIGHT SLIDER - NUDE",
      "picture1": "assets/images/shoes/journey/nude/1.png",
      "picture2": "assets/images/shoes/journey/nude/2.png",
      "picture3": "assets/images/shoes/journey/nude/3.png",
      "reviews": 1,
      "price": 650,
    },
  ];
}
